# Generated by Django 6.0 on 2025-12-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('rule_config', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('NEED_INFO', 'Need Info'), ('BLOCKED', 'Blocked')], default='NEED_INFO', max_length=20)),
                ('verification_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
